Pruebamvc
Darly09/book_fantasy pull request #7
Opened 2023-05-20 05:05 UTC by JuanP0329

2023-05-26 21:05 UTC, FelipeVelasquez1802 requested changes

2023-05-26 21:05 UTC, FelipeVelasquez1802 commented on backend/controller/books/GetBooksController.js
Oye por qué estamos subiendo archivos que estan vacios al repositorio?
Esto será controlado en un siguiente feature? @JuanP0329

2023-05-26 21:05 UTC, FelipeVelasquez1802 commented on backend/index.js
> +const app = express ();
Puedes por favor quitar el espacio que esta entre la constante express y los parentesis

```javascript
const app = express ();
``` 

Y lo correcto es 
```JavaScript
const app = express();
```
Esto lo puedes solucionar indentando el codigo @JuanP0329

2023-05-27 21:48 UTC, JuanP0329 commented on backend/controller/books/GetBooksController.js
Si esto sera controlado en un siguiente feature, por @Alejandro2796

2023-05-27 22:04 UTC, JuanP0329 commented on backend/index.js
> +const app = express ();
ya se resolvió el código.

2023-05-27 23:06 UTC, FelipeVelasquez1802 approved these changes

2023-05-27 23:06 UTC, merged